on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: yarn-${{ hashFiles('yarn.lock') }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: yarn
      - run: aws s3 sync s3://${{ secrets.S3_BUCKET }}/browser-runner wasm-dist/browser-runner
      - run: yarn prod
      - run: aws s3 sync dist s3://${{ secrets.S3_BUCKET }}/webapp-assets

      # https://stackoverflow.com/a/18194523
      - run: svn checkout https://github.com/robot-rumble/backend/trunk/public/images

      - run: yarn prod-cli
      - run: aws s3 sync cli-dist s3://${{ secrets.S3_BUCKET }}/cli-assets
